#!/usr/bin/env bash
# Generates frontend/src/generated/version.ts from VERSION + git info
set -euo pipefail

ROOT="$(dirname "$0")/.."
VERSION=$(cat "$ROOT/VERSION" 2>/dev/null || echo "0.0.0")
COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(git log -1 --format=%ai 2>/dev/null || date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$ROOT/frontend/src/generated/version.ts" <<EOF
// Auto-generated by scripts/generate-version.sh — do not edit
export const APP_VERSION = '${VERSION}';
export const APP_COMMIT = '${COMMIT}';
export const APP_DATE = '${DATE}';
EOF
